[package]
name = "digest"
version = "0.1.0"
authors = ["CoBloX <hello@coblox.tech>"]
edition = "2018"

[dependencies]
digest-macro-derive = { path = "../digest-macro-derive" }
hex = "0.4"

[dev-dependencies]
multihash = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
