name: Extract version from release branch
description: Extracts the version of a component from the release branch name
inputs:
  prefix:
    description: 'The prefix that if removed from the branch name yields the version'
    required: true
outputs:
  version:
    description: 'The version that was extracted from the branch name'
    value: ${{ steps.extract-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: extract-version
      run: |
        BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
        VERSION=${BRANCH_NAME#${{ inputs.prefix }}}

        echo "::set-output name=version::$VERSION"
      shell: bash
