name: "Release cnd"

on:
  release:
    types: [created]

jobs:
  release:
    if: startsWith(github.event.release.tag_name, 'cnd-') # only trigger this if we released cnd
    name: Release cnd
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tagged commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.BOTTY_GITHUB_TOKEN }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Build ${{ matrix.os }} release binary
        id: build
        run: cargo build --release --package cnd

      - name: Extract version from branch name
        id: extract-version
        uses: ./.github/actions/trim-front
        with:
          string: ${{ github.event.release.tag_name }}
          prefix: cnd-

      - name: Create release archive
        id: create-archive
        uses: ./.github/actions/create-release-archive
        with:
          binary: cnd
          version: ${{ steps.extract-version.outputs.trimmed }}

      - name: Upload ${{ matrix.os }} release binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOTTY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.create-archive.outputs.archive }}
          asset_name: ${{ steps.create-archive.outputs.archive }}
          asset_content_type: application/gzip

      - name: Login to docker
        if: matrix.os == 'ubuntu-latest'
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build cnd docker image as ${{ steps.extract-version.outputs.trimmed }} and latest
        if: matrix.os == 'ubuntu-latest'
        run: |
          VERSION="${{ steps.extract-version.outputs.trimmed }}"
          docker build . -t comitnetwork/cnd:$VERSION -t comitnetwork/cnd:latest

      - name: Test docker image by starting it and curling the cnd API
        if: matrix.os == 'ubuntu-latest'
        run: |
          VERSION="${{ steps.extract-version.outputs.trimmed }}"
          echo "::starting docker-container comitnetwork/cnd:$VERSION"
          docker run --publish 8000:8000 --detach --name cnd_container comitnetwork/cnd:$VERSION
          curl --fail localhost:8000/
          echo "::cnd API curled successfully"
          docker stop cnd_container

      - name: Publish docker image as ${{ steps.extract-version.outputs.trimmed }} and latest
        if: matrix.os == 'ubuntu-latest'
        run: |
          VERSION="${{ steps.extract-version.outputs.trimmed }}"
          docker push comitnetwork/cnd:$VERSION
          docker push comitnetwork/cnd:latest
